# This is a basic workflow to help you get started with Actions

name: deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn
          yarn build --mode=github

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.EMIYAGM_GITHUB_TOKEN }}
          publish_dir: ./dist
